name: Debug your Workflows
description: |
  This action helps you debug your workflows by running an SSH server,
  accessible through temporary cloudflare tunnels, and restricted to your users
  -- the SSH keys registered to the user that started the workflow at GitHub.
author: Emmanuell Frecon <efrecon+github@gmail.com>
branding:
  icon: terminal
  color: red

runs:
  using: composite
  steps:
    - name: SSHd
      id: debug
      shell: bash
      env:
        CF_SSHD_BRANCH: ${{ github.action_ref }}
      run: |
        curl -sSL "https://github.com/efrecon/sshd-cloudflared/raw/${CF_SSHD_BRANCH:-main}/install.sh" |
          sh -s -- -r -i "entrypoint.sh" -- -g "${{ github.actor }}"