name: Debug your Workflows
description: |
  This action helps you debug your workflows by running an SSH server,
  accessible through temporary cloudflare tunnels, and restricted to your users
  -- the SSH keys registered to the user that started the workflow at GitHub.
author: Emmanuell Frecon <efrecon+github@gmail.com>
branding:
  icon: terminal
  color: red

inputs:
  user:
    description: |
      The GitHub user to allow access to the SSH server. By default, this will
      be the user that triggered the workflow.
    required: false
    default: ${{ github.actor }}

runs:
  using: composite
  steps:
    - name: SSHd
      id: debug
      shell: bash
      env:
        CF_SSHD_BRANCH: ${{ github.action_ref }}
        CF_SSHD_USERNAME: ${{ inputs.user }}
      run: |
        curl -sSL "https://github.com/efrecon/sshd-cloudflared/raw/${CF_SSHD_BRANCH:-main}/install.sh" |
          sh -s -- -r -i "entrypoint.sh" -- -g "$CF_SSHD_USERNAME"