name: generic build

on:
  workflow_call:
    inputs:
      registry:
        description: 'Docker registry'
        type: string
        default: 'ghcr.io'
      version:
        description: 'cloudflared version'
        type: string
        default: 'latest'
      platforms:
        description: 'Platforms to build for, comma separated list of arch/os pairs'
        required: false
        type: string
        default: 'linux/amd64'
      runs-on:
        description: 'Runner to use'
        required: false
        type: string
        default: 'ubuntu-latest'
    secrets:
      username:
        description: 'username at registry'
        required: false
      password:
        description: 'password at registry'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      -
        name: Login at registry
        uses: docker/login-action@v3
        if: ${{ ! startsWith(inputs.registry, 'localhost') }}
        with:
          registry: ${{ inputs.registry }}
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Check Presence
        id: present
        run: |
          if docker manifest inspect "${{ inputs.registry }}/${{ github.repository_owner }}/cloudflared:${{ inputs.version }}" 2>/dev/null; then
            printf "present=true\n" >> "$GITHUB_OUTPUT"
          else
            printf "present=false\n" >> "$GITHUB_OUTPUT"
          fi
      -
        name: Build cloudflared Image
        uses: docker/build-push-action@v5
        id: cloudflared
        if: steps.present.outputs.present == 'false'
        with:
          push: true
          file: Dockerfile.cloudflared
          platforms: ${{ inputs.platforms }}
          tags: |
            ${{ inputs.registry }}/${{ github.repository_owner }}/cloudflared:${{ inputs.version }}
          build-args: |
            CLOUDFLARED_VERSION=${{ inputs.version }}
      -
        name: Build and push Base Image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile.base
          platforms: ${{ inputs.platforms }}
          build-args: |
            BASEIMAGE=${{ inputs.registry }}/${{ github.repository_owner }}/cloudflared:${{ inputs.version }}
          tags: |
            ${{ inputs.registry }}/${{ github.repository }}-base:${{ inputs.version }}
            ${{ inputs.registry }}/${{ github.repository }}-base:latest
      -
        name: Build and push DevEnv Image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          platforms: ${{ inputs.platforms }}
          build-args: |
            BASEIMAGE=${{ inputs.registry }}/${{ github.repository }}-base:${{ inputs.version }}
          tags: |
            ${{ inputs.registry }}/${{ github.repository }}:${{ inputs.version }}
            ${{ inputs.registry }}/${{ github.repository }}:latest
