name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.latest }}
    steps:
      -
        name: Latest Version
        id: version
        uses: efrecon/gh-action-releases@main
        with:
          project: cloudflare/cloudflared

  # When pushing to the main branch, we (re)generate images, tagged with
  # "latest"
  ghcr:
    uses: ./.github/workflows/_build.yml
    with:
      registry: ghcr.io
      platforms: linux/amd64,linux/arm64,linux/i386
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}
    if: github.ref_name == 'main'
    needs: version

  # When pushing to feature branches, we test stuff on the platform of the
  # runner only, using a local registry so as to be able to push and pull to
  # Docker from the builder steps.
  build:
    uses: ./.github/workflows/_build.yml
    with:
      registry: localhost:5000
      platforms: linux/amd64
    if: github.ref_name != 'main'
    needs: version
