name: Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  ghcr:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push Base Image
        id: base
        uses: docker/build-push-action@v3
        with:
          push: ${{ env.GITHUB_REF_NAME == 'main' }}
          load: ${{ env.GITHUB_REF_NAME != 'main' }}
          file: Dockerfile.base
          platforms: linux/amd64,linux/arm64,linux/i386
          tags: ghcr.io/efrecon/sshd-cloudflared-base:latest
      -
        name: Build and push DevEnv Image
        id: devenv
        uses: docker/build-push-action@v3
        with:
          push: ${{ env.GITHUB_REF_NAME == 'main' }}
          load: ${{ env.GITHUB_REF_NAME != 'main' }}
          file: Dockerfile
          platforms: linux/amd64,linux/arm64,linux/i386
          tags: ghcr.io/efrecon/sshd-cloudflared:latest
