name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - feature/*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./
